CREATE TABLE IF NOT EXISTS subscribers
(id INT(11) AUTO_INCREMENT PRIMARY KEY,
 email VARCHAR(100) UNIQUE NOT NULL,
 signup_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
